# Generated by Django 4.2.1 on 2023-06-04 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
